### PR TITLE
outbound: add request builder

### LINKED ISSUE #846: finer grained request builder
Per @hzxuzhonghu [comment](https://github.com/istio/ztunnel/pull/832#discussion_r1508386863) there are a lot of struct literals in outbound build_request. We should consider implementing a finer grained function just for building requests to remove the literals.

### PR DESCRIPTION
**Pull request by daixiang0**
Fix #846 

Introduce typed-builder to reduce builder codes and make all struct easy to build.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
I think this is a regression in safety and behavior. It bloats the code and adds indirection via macro, and makes it possible to forget to set fields - less safe than today. The only real benefit is we can omit the None fields, which I view as a downside - being explicit is important here

**Comment by daixiang0** [comment]
I want to use existed crate to reduce the builder codes, here is an example without any crate:

```
struct RequestBuilder {
    method: String,
    url: String,
    headers: Vec<(String, String)>,
    body: Option<String>,
}

impl RequestBuilder {
    pub fn new(method: &str, url: &str) -> Self {
        Self {
            method: method.to_string(),
            url: url.to_string(),
            headers: Vec::new(),
            body: None,
        }
    }

    pub fn add_header(mut self, key: &str, value: &str) -> Self {
        self.headers.push((key.to_string(), value.to_string()));
        self
    }

    pub fn set_body(mut self, body: &str) -> Self {
        self.body = Some(body.to_string());
        self
    }

    pub fn build(self) -> Result<Request, &'static str> {
        // Validate and construct the actual request here
        // For demonstration purposes, let's assume we have a Request struct
        // with fields method, url, headers, and body.
        // You can replace this with your actual implementation.

        // Example:
        let request = Request {
            method: self.method,
            url: self.url,
            headers: self.headers,
            body: self.body,
        };

        // Validate the request (imaginary validation function)
        if request_is_valid(&request) {
            Ok(request)
        } else {
            Err("Invalid request")
        }
    }
}

// Example usage:
let request = RequestBuilder::new("GET", "https://api.example.com")
    .add_header("Authorization", "Bearer token")
    .set_body("Hello, world!")
    .build()?;

println!("Request: {:?}", request);
```

**Comment by howardjohn** [comment]
My concern is not with the crate it's with the concept in general

**Comment by daixiang0** [comment]
Sure, if the issue is not planed, feel free to close all.

**Comment by daixiang0** [comment]
Add @hzxuzhonghu as the issue requester.

**Pull request closed without merging**
