### PR TITLE
Support setting the ports in environment variables

### PR DESCRIPTION
**Pull request by ymesika**
Environment variable with highest priority. If not set, same as before.

### CODE REVIEW

**Comment by shashankram** [comment]
Thanks @ymesika for this change. This is a useful customization in environments needing better control over the proxy ports.

**Review by howardjohn — COMMENTED** [review]
Can you expand on the use case a bit? I am mostly curious why we only set these 3 ports?

Also why we need env var for stats and admin, which already have a setting in proxy config. AFAIK the readiness port is the same Envoy uses which is also hardcoded, so why does ztunnel have more flexibility than envoy?

**Comment by shashankram** [comment]
> Can you expand on the use case a bit? I am mostly curious why we only set these 3 ports?
> 
> Also why we need env var for stats and admin, which already have a setting in proxy config. AFAIK the readiness port is the same Envoy uses which is also hardcoded, so why does ztunnel have more flexibility than envoy?

I don't think we need overrides for the admin port, but it would make sense to provide the ability to configure the stats port so pilot-agent and ztunnel can co-exist on the same pod, primarily for users relying on the existing istio-dns proxy capability for custom DNS resolution. For this specific scenario, to use the mesh config yaml we'd need 2 separate copies of it with different ports. Having an env var to override the default port seems more flexible at the cost of reduced complexity of needing multiple mesh config files.

**Comment by howardjohn** [comment]
I am not sure why having 2 configs for 2 different things is a problem.

**Comment by shashankram** [comment]
> I am not sure why having 2 configs for 2 different things is a problem.

It's not a problem, but rather relatively inconvenient compared to updating the env var without needing to maintain multiple config files. If you prefer having 2 separate config files for this scenario, I don't envision needing to configure these ports via env vars.

**Comment by howardjohn** [comment]
IMO proxy config is the standard way to configure things in Istio and we have used it here, so we should be consistent.

**Comment by ymesika** [comment]
Closing in favor of having different configs.

**Pull request closed without merging**
