### PR TITLE
Update Hyper to 1.0.0-rc4

### PR DESCRIPTION
**Pull request by howardjohn**
This is 1 step closer to 1.0.0....

The main change is they made their own Read/Write types, so we need to
wrap a bunch of things in `TokioIo`. NBD.

### CODE REVIEW

**Comment by howardjohn** [comment]
note to self: need to sort key usage

**Comment by hzxuzhonghu** [comment]
what's the improvement

**Comment by howardjohn** [comment]
Nothing but we need to update eventually since this will become the 1.0.0.
Better adopt to the breaking change sooner than later.

Also this bumps the boringssl library which Nate said fixed OSX build
although I couldn't verify myself.

**Comment by ericvn** [comment]
And hoping this fixes the failure in https://github.com/istio/ztunnel/pull/656.

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
