### PR TITLE
Removed unused golang related scripts and variables

### PR DESCRIPTION
**Pull request by litong01**
These golang related variables and scripts do not seem to be used any more, removing them to make the build process less confusing.
Signed-off-by: Tong Li <litong01@us.ibm.com>

### CODE REVIEW

**Comment by litong01** [comment]
> These come from common-files, this will be reverted automatically even if we merge.
> 
> These are common to all repos, regardless of language

@howardjohn  John, are they copied from other repo?

**Comment by howardjohn** [comment]
istio/common-files

**Comment by ericvn** [comment]
@litong01 Files in the common directory are: https://github.com/istio/common/blob/master/common/Makefile.common.mk#L105

**Comment by litong01** [comment]
Not needed since common files pulled from istio/common

**Pull request closed without merging**
