### PR TITLE
logs: hide dns logs by default

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/ztunnel/issues/876

### CODE REVIEW

**Review by bleggett — APPROVED** [review]
We should explicitly document how to re-enable them for debugging but I notice that we don't have any info around RUST_LOG overrides in LOCAL.md yet, and we have several PRs out for that already, so that can come after.

**Comment by howardjohn** [comment]
> We should explicitly document how to re-enable them for debugging but I notice that we don't have any info around RUST_LOG overrides in LOCAL.md yet, and we have several PRs out for that already, so that can come after.

I document it in https://github.com/istio/ztunnel/pull/874 (though not specifically the obscure DNS target name. I actually wonder if we can/should overwrite it to obscure the `hickory_...` junk)

**Comment by bleggett** [comment]
> > We should explicitly document how to re-enable them for debugging but I notice that we don't have any info around RUST_LOG overrides in LOCAL.md yet, and we have several PRs out for that already, so that can come after.
> 
> I document it in #874 (though not specifically the obscure DNS target name. I actually wonder if we can/should overwrite it to obscure the `hickory_...` junk)

Ah I missed that, ty.

`DEBUG_DNS` et al would be nice but as long as we document the particular `hickory` incantations required it doesn't have to be pretty.

**Review by ilrudie — APPROVED** [review]
LGTM, agree about documenting how to turn back on but I am ok with having that in the access log PR where that section is being written

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
