### PR TITLE
bump thiserror to 1.0.38

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fix https://github.com/istio/ztunnel/issues/307

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM but I am not sure it fixes it? Or I don't understand why at least (see comment on issue)

**Comment by hzxuzhonghu** [comment]
The build complains thiserror

**Comment by howardjohn** [comment]
But updating is just clearing the build cache I suspect

**Comment by howardjohn** [comment]
The real issue seems to be a cache invalidation issue in cargo

**Pull request merged**
