### PR TITLE
Remove "useless vec!"s

### PR DESCRIPTION
**Pull request by Stevenjin8**
This was added in 1.29. Not sure how we went so long without this issue appearing.

https://rust-lang.github.io/rust-clippy/master/index.html#/useless_vec

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
I think its probably default in the new rust version and we updatd. can you run `cargo clippy --fix; cargo fmt`? Or `git apply <(curl -sL "https://gcsweb.istio.io/gcs/istio-prow/pr-logs/pull/istio_ztunnel/670/test_ztunnel/1695127531990028288/artifacts/check-clean-repo-diff.patch")`

**Comment by howardjohn** [comment]
:+1: thanks

**Comment by Stevenjin8** [comment]
> I think its probably default in the new rust version and we updatd. can you run `cargo clippy --fix; cargo fmt`? Or `git apply <(curl -sL "https://gcsweb.istio.io/gcs/istio-prow/pr-logs/pull/istio_ztunnel/670/test_ztunnel/1695127531990028288/artifacts/check-clean-repo-diff.patch")`

Jinx

**Pull request merged**
