### PR TITLE
zero copy between two socket for passthrough mode

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
It uses a lib `https://github.com/zhboner/realm`,  which implement zero-copy by splice

### CODE REVIEW

**Comment by howardjohn** [comment]
Running with the new benchmarks:

```
throughput/tcp/10485760 time:   [38.801 ms 41.746 ms 44.663 ms]
                        thrpt:  [223.90 MiB/s 239.54 MiB/s 257.72 MiB/s]
                 change:
                        time:   [+22.433% +34.381% +48.079%] (p = 0.00 < 0.05)
                        thrpt:  [-32.468% -25.585% -18.323%]
                        Performance has regressed.
```

But running in real world with iperf3:

master: 12Gb/s
zero-copy: 36Gb/s

So clearly something suspicious with the benchmark logic...

**Comment by howardjohn** [comment]
ok with some tweaks on the benchmark:

```
throughput/tcp          time:   [1.6780 ms 1.8091 ms 1.9420 ms]
                        thrpt:  [5.0285 GiB/s 5.3980 GiB/s 5.8198 GiB/s]
                 change:
                        time:   [-72.679% -70.012% -67.213%] (p = 0.00 < 0.05)
                        thrpt:  [+205.00% +233.47% +266.02%]
                        Performance has improved.
```

Which aligns with manual numbers

**Comment by hzxuzhonghu** [comment]
good to see, 
>ok with some tweaks on the benchmark:

What did you tune?

**Comment by howardjohn** [comment]
https://github.com/istio/ztunnel/pull/175

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
I don't know why the old throughput test didn't work well for this one, but the test client implementation was pretty broken..

**Pull request merged**
