### PR TITLE
Bump rust version to 1.78

### PR DESCRIPTION
**Pull request by howardjohn**
This matches the new docker image

### CODE REVIEW

**Comment by howardjohn** [comment]
maybe we shouldn't dothis since we don't require 1.78, and this will make it fail on 1.77?

**Comment by bleggett** [comment]
Yeah I think we need to track our CI version/`build-tools` version exactly in the cargo.toml

**Comment by howardjohn** [comment]
rust-version is the 'The minimal supported Rust version.' We run fine on 1.77, do we really want to say you MUST have 1.78?

Build tools is fine since that is managed. I don't personally care since I always use `latest`. But seems a bit excessive

**Comment by bleggett** [comment]
> rust-version is the 'The minimal supported Rust version.' We run fine on 1.77, do we really want to say you MUST have 1.78?

I think our min version can only be the min version we actually build and test with.

People are free to try and change it and set it lower, but our floor sort of has to be what we use in CI.

**Pull request closed without merging**
