### PR TITLE
bump dependency

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
@hanxiaop Why does it need to be backported

**Comment by hanxiaop** [comment]
> @hanxiaop Why does it need to be backported

There are some errors when updating common files of 1.20 ztunnel repo. See https://github.com/istio/ztunnel/pull/731#issuecomment-1818150804. Or should we only fix the usage?

**Comment by hzxuzhonghu** [comment]
We can fix the lint.

**Comment by hanxiaop** [comment]
> We can fix the lint.

Sounds good, I'll revise

**Pull request merged**
